# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Simulacion.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1197, 937)
        self.Nuevo_Boton = QPushButton(Form)
        self.Nuevo_Boton.setObjectName(u"Nuevo_Boton")
        self.Nuevo_Boton.setGeometry(QRect(930, 10, 151, 31))
        font = QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Nuevo_Boton.setFont(font)
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(640, 10, 71, 31))
        font1 = QFont()
        font1.setPointSize(12)
        self.label.setFont(font1)
        self.Tiempo_TB = QTextBrowser(Form)
        self.Tiempo_TB.setObjectName(u"Tiempo_TB")
        self.Tiempo_TB.setGeometry(QRect(710, 10, 61, 31))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        font2.setWeight(75)
        self.Tiempo_TB.setFont(font2)
        self.Listos_TW = QTableWidget(Form)
        self.Listos_TW.setObjectName(u"Listos_TW")
        self.Listos_TW.setGeometry(QRect(10, 80, 721, 161))
        self.Listos_TW.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.Listos_TW.setRowCount(0)
        self.Listos_TW.setColumnCount(0)
        self.Listos_TW.horizontalHeader().setCascadingSectionResizes(True)
        self.Listos_TW.horizontalHeader().setDefaultSectionSize(120)
        self.Listos_TW.verticalHeader().setVisible(False)
        self.Terminados_TW = QTableWidget(Form)
        self.Terminados_TW.setObjectName(u"Terminados_TW")
        self.Terminados_TW.setGeometry(QRect(740, 80, 451, 461))
        self.Terminados_TW.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.Terminados_TW.horizontalHeader().setCascadingSectionResizes(True)
        self.Terminados_TW.verticalHeader().setVisible(False)
        self.Bloqueados_TW = QTableWidget(Form)
        self.Bloqueados_TW.setObjectName(u"Bloqueados_TW")
        self.Bloqueados_TW.setGeometry(QRect(10, 410, 721, 131))
        self.Bloqueados_TW.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.Bloqueados_TW.horizontalHeader().setCascadingSectionResizes(True)
        self.Bloqueados_TW.horizontalHeader().setDefaultSectionSize(160)
        self.Bloqueados_TW.verticalHeader().setVisible(False)
        self.label_2 = QLabel(Form)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 10, 151, 31))
        self.label_2.setFont(font1)
        self.Nuevos_TB = QTextBrowser(Form)
        self.Nuevos_TB.setObjectName(u"Nuevos_TB")
        self.Nuevos_TB.setGeometry(QRect(160, 10, 61, 31))
        self.Nuevos_TB.setFont(font2)
        self.label_3 = QLabel(Form)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(740, 50, 451, 31))
        self.label_3.setFont(font1)
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_4 = QLabel(Form)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 50, 721, 31))
        self.label_4.setFont(font1)
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_5 = QLabel(Form)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 240, 721, 31))
        self.label_5.setFont(font1)
        self.label_5.setAlignment(Qt.AlignCenter)
        self.Ejecucion_TW = QTableWidget(Form)
        self.Ejecucion_TW.setObjectName(u"Ejecucion_TW")
        self.Ejecucion_TW.setGeometry(QRect(10, 280, 721, 101))
        self.Ejecucion_TW.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.Ejecucion_TW.setColumnCount(0)
        self.Ejecucion_TW.horizontalHeader().setCascadingSectionResizes(True)
        self.Ejecucion_TW.horizontalHeader().setDefaultSectionSize(118)
        self.Ejecucion_TW.verticalHeader().setVisible(False)
        self.label_6 = QLabel(Form)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 380, 721, 31))
        self.label_6.setFont(font1)
        self.label_6.setAlignment(Qt.AlignCenter)
        self.Quantum_TB = QTextBrowser(Form)
        self.Quantum_TB.setObjectName(u"Quantum_TB")
        self.Quantum_TB.setGeometry(QRect(860, 10, 61, 31))
        self.Quantum_TB.setFont(font2)
        self.label_7 = QLabel(Form)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(780, 10, 71, 31))
        self.label_7.setFont(font1)
        self.Memoria_TW = QTableWidget(Form)
        if (self.Memoria_TW.columnCount() < 28):
            self.Memoria_TW.setColumnCount(28)
        __qtablewidgetitem = QTableWidgetItem()
        self.Memoria_TW.setHorizontalHeaderItem(0, __qtablewidgetitem)
        if (self.Memoria_TW.rowCount() < 11):
            self.Memoria_TW.setRowCount(11)
        self.Memoria_TW.setObjectName(u"Memoria_TW")
        self.Memoria_TW.setGeometry(QRect(10, 570, 1181, 361))
        self.Memoria_TW.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.Memoria_TW.setRowCount(11)
        self.Memoria_TW.setColumnCount(28)
        self.Memoria_TW.horizontalHeader().setDefaultSectionSize(42)
        self.Memoria_TW.verticalHeader().setVisible(False)
        self.label_8 = QLabel(Form)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 540, 1101, 31))
        self.label_8.setFont(font1)
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(Form)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(240, 10, 101, 31))
        self.label_9.setFont(font1)
        self.NextID_TB = QTextBrowser(Form)
        self.NextID_TB.setObjectName(u"NextID_TB")
        self.NextID_TB.setGeometry(QRect(340, 10, 51, 31))
        self.NextID_TB.setFont(font2)
        self.label_10 = QLabel(Form)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(420, 10, 141, 31))
        self.label_10.setFont(font1)
        self.NextTam_TB = QTextBrowser(Form)
        self.NextTam_TB.setObjectName(u"NextTam_TB")
        self.NextTam_TB.setGeometry(QRect(560, 10, 51, 31))
        self.NextTam_TB.setFont(font2)
        self.Detener_Boton = QPushButton(Form)
        self.Detener_Boton.setObjectName(u"Detener_Boton")
        self.Detener_Boton.setGeometry(QRect(1090, 10, 101, 31))
        font3 = QFont()
        font3.setPointSize(11)
        font3.setBold(False)
        font3.setWeight(50)
        self.Detener_Boton.setFont(font3)

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Simulaci\u00f3n", None))
        self.Nuevo_Boton.setText(QCoreApplication.translate("Form", u"Nueva Simulaci\u00f3n", None))
        self.label.setText(QCoreApplication.translate("Form", u"Tiempo: ", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"Procesos en Nuevos:", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"Procesos Terminados", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"Procesos en Listos", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"Proceso en Ejecucion", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"Proceso en Bloqueados", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"Quantum:", None))
        ___qtablewidgetitem = self.Memoria_TW.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("Form", u"Marco", None));
        self.label_8.setText(QCoreApplication.translate("Form", u"Memoria", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"ID siguiente:", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"Tama\u00f1o siguiente:", None))
        self.Detener_Boton.setText(QCoreApplication.translate("Form", u"Detener", None))
    # retranslateUi

